# This playbook will do mon kill drill test case, and if in manual
# mode, it will prompt to ask if you want to recover it.

- include: ../../common/next.yml
  vars:
    case_name: "CASE: Ceph monitor down by error opening data directory on {{ random_hosts }}"

- name: "Drill the case"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: storage
        tasks_from: damage_mon
      when:
        - execute == "y" or execute == true

- include: ../../common/ask.yml

- name: "Recover the fault"
  hosts: "{{ random_hosts }}"
  gather_facts: true
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
    recovery: "{{ hostvars['localhost']['recovery'] }}"
  tasks:
    - include_role:
        name: storage
        tasks_from: recover_damage_mon
      when:
        - mode == "auto" or recovery == "y" or recovery == true
        - execute == "y" or execute == true
